-- ============================================================
-- DONNÉES — Thématiques et scénarios du simulateur Apézeo
-- FICHIER COMPLET : 7 thématiques, 21 scénarios.
-- Remplace simulateur_donnees_scenarios_partiel.sql (à ne pas exécuter
-- si vous avez déjà lancé celui-ci — sinon vous auriez un conflit de
-- clé primaire ; dans ce cas, videz les deux tables avant de relancer
-- ce fichier-ci : truncate simulateur.scenarios, simulateur.themes cascade;)
--
-- À exécuter après simulateur_schema_et_rls.sql (les tables
-- simulateur.themes et simulateur.scenarios doivent déjà exister).
-- ============================================================

insert into simulateur.themes (code, nom, description, icone, ordre) values
  ('desorientation', 'Désorientation temporo-spatiale',
   'Confusion sur le lieu, le temps ou les proches ; apaiser sans confronter frontalement la réalité.',
   'clock', 1),
  ('soins', 'Soins du quotidien & refus',
   'Toilette, repas, médicaments ; accompagner un refus sans imposer ni infantiliser.',
   'drop', 2),
  ('reconnaissance', 'Reconnaissance & lien affectif',
   'Fausses reconnaissances, confusions d''identité ; entre validation et vérité, un équilibre délicat.',
   'people', 3),
  ('agitation', 'Agitation et troubles du comportement',
   'Déambulation, montée de tension, agressivité soudaine ; chercher la cause avant de gérer le symptôme.',
   'wave', 4),
  ('hallucinations', 'Hallucinations et perceptions inhabituelles',
   'Voir, entendre ou sentir des choses qui n''existent pas pour autrui ; accueillir la perception sans la renforcer ni la nier brutalement.',
   'eye', 5),
  ('stress-post-traumatique', 'Stress post-traumatique',
   'Un geste de soin, un bruit soudain (porte qui claque) peuvent réveiller un vécu traumatique ancien ; accompagner sans forcer ni braquer.',
   'shield', 6),
  ('depression', 'Dépression et vécu de deuils du sujet âgé',
   'Deuils successifs, sentiment d''inutilité, bilan de vie douloureux ; écouter sans minimiser ni forcer un optimisme de façade.',
   'raincloud', 7);

insert into simulateur.scenarios
  (code, theme_code, nom, age, difficulte, contexte, accroche, initiales, humeur_initiale, replique_ouverture, profil_clinique, ordre)
values
  ('lucienne', 'desorientation', 'Lucienne R.', 84, 'facile',
   'Alzheimer stade modéré · déjeuner',
   'Convaincue de devoir aller chercher ses petits-enfants à l''école, elle s''agite à l''heure du déjeuner.',
   'LR', 'anxieuse',
   'Ah... vous êtes qui déjà ? Il faut que je descende, ma fille elle m''attend en bas avec la voiture, elle va être en retard pour l''école à cause de moi... Vous pouvez m''aider à trouver mon manteau ?',
   'Lucienne R., 84 ans, résidente depuis 3 ans, Alzheimer stade modéré. C''est l''heure du déjeuner. Elle est convaincue de devoir aller chercher ses petits-enfants à la sortie de l''école, ou que sa fille Marie-Claude l''attend en bas avec la voiture. Elle ne se souvient pas être en EHPAD ni que ses petits-enfants sont aujourd''hui adultes. Une contradiction frontale ou une rafale de questions logiques (heure exacte, lieu précis) accroissent sa confusion et sa détresse : elle peut se lever, vouloir sortir, hausser la voix, pleurer. À l''inverse, un soignant qui valide son émotion (l''inquiétude, l''amour pour sa famille) sans forcément confirmer ni infirmer les faits, et propose une redirection douce et concrète, l''apaise progressivement et peut même faire émerger de la tendresse dans l''échange.',
   1),
  ('henri', 'desorientation', 'Henri M.', 81, 'intermediaire',
   'Démence mixte · veut sortir de l''unité',
   'Persuadé que son épouse décédée l''attend pour le déjeuner, il insiste pour sortir.',
   'HM', 'opposante',
   'Bon, je vais y aller maintenant, Paulette m''attend pour manger, elle n''aime pas quand je suis en retard. Vous pouvez m''ouvrir la porte s''il vous plaît ?',
   'Henri M., 81 ans, résident depuis 8 mois, démence mixte à un stade modéré. Il est convaincu que son épouse Paulette, décédée il y a 4 ans, l''attend pour le déjeuner à la maison, et il se dirige avec insistance vers la porte de sortie de l''unité, sac à la main. Il est déterminé plutôt qu''anxieux : il devient irritable et insiste davantage si on lui bloque physiquement le passage ou si on lui dit sèchement que c''est impossible. Il se laisse en revanche détourner par une proposition concrète et valorisante (une tâche à ''terminer'' avant de partir, un café en attendant que ''Paulette finisse de préparer le repas'') associée à une présence rassurante, sans jamais le contredire brutalement sur le fait que Paulette n''est plus là.',
   2),
  ('georgette', 'desorientation', 'Georgette V.', 90, 'expert',
   'Alzheimer avancé · trouble du langage associé',
   'Désorientée et incapable de trouver ses mots : la communication elle-même devient un obstacle.',
   'GV', 'confuse',
   'Il faut... il faut que je... le train, le. (elle s''arrête, cherchant ses mots, visiblement frustrée) ...vous comprenez pas, j''ai pas le temps !',
   'Georgette V., 90 ans, résidente depuis 2 ans, Alzheimer avancé associé à une aphasie modérée (trouble du langage). Elle est désorientée dans le temps, persuadée de devoir prendre ''le train'' pour une raison qu''elle peine à formuler, et cherche activement ses mots sans les trouver, ce qui ajoute de la frustration à sa confusion. Elle peut s''énerver contre elle-même autant que contre le soignant si celui-ci la presse de ''finir sa phrase'' ou termine ses phrases à sa place de façon systématique. Un soignant qui ralentit son propre débit, laisse de vrais silences pour qu''elle cherche ses mots, valide ses tentatives (''je vois que vous voulez me dire quelque chose d''important'') et se concentre sur l''émotion sous-jacente plutôt que sur le contenu logique, obtient un apaisement progressif malgré la persistance du trouble du langage.',
   3),

  ('simone', 'soins', 'Simone L.', 86, 'facile',
   'Troubles cognitifs légers · refus du petit-déjeuner',
   'Elle refuse de manger, préférant attendre son mari ; une opposition douce, facile à désamorcer.',
   'SL', 'calme',
   'Non merci, je n''ai pas faim maintenant. J''attends Fernand, il ne devrait pas tarder, on mangera ensemble.',
   'Simone L., 86 ans, résidente depuis 1 an, troubles cognitifs légers à modérés d''origine mixte. Ce matin, elle refuse son petit-déjeuner, dit qu''elle n''a pas faim et préfère attendre ''que Fernand rentre'' (son mari, décédé) pour manger avec lui. Son opposition reste douce, sans agressivité, mais elle peut se braquer si on insiste lourdement (''il faut manger, c''est important pour la santé'') ou si on la brusque. Elle se laisse assez facilement convaincre si on prend le temps de s''asseoir avec elle, de parler un peu de Fernand avec tendresse, et de lui proposer de ''goûter juste un peu en attendant''.',
   1),
  ('robert', 'soins', 'Robert T.', 79, 'intermediaire',
   'Démence vasculaire · toilette du matin',
   'Ancien contremaître, fier et méfiant, il refuse catégoriquement la toilette du matin.',
   'RT', 'opposante',
   'Non, non et non ! Je me laverai tout seul, je ne suis pas un invalide que je sache. Sortez de ma chambre, vous entendez ?',
   'Robert T., 79 ans, résident en EHPAD, démence vasculaire à un stade modéré à sévère. Ancien contremaître dans le bâtiment, homme fier et attaché à son autonomie et à sa dignité. Le matin, le soignant vient pour la toilette. Robert refuse catégoriquement au premier abord : il se sent infantilisé et perd patience si on le presse, si on lui impose un ordre, ou si on ignore son refus en insistant frontalement ; il peut alors devenir agressif verbalement (''fichez le camp'', ''je ne suis pas un gamin''). S''il se sent respecté dans son rythme, si on lui laisse de vrais choix (se laver seul avec assistance discrète, choisir l''ordre des gestes, décider du moment à quelques minutes près), et si le soignant reconnaît sa compétence et son autonomie passées, il accepte progressivement de coopérer, parfois avec une pointe d''humour bourru.',
   2),
  ('ahmed', 'soins', 'Ahmed K.', 83, 'expert',
   'Démence à corps de Lewy · méfiance envers les médicaments',
   'Convaincu qu''on cherche à l''empoisonner, il refuse ses médicaments avec une méfiance bien réelle.',
   'AK', 'opposante',
   'Je ne prendrai pas ça. Vous croyez que je ne vois pas ce que vous essayez de faire ? Je ne suis pas idiot.',
   'Ahmed K., 83 ans, résident depuis 6 mois, démence à corps de Lewy avec fluctuations cognitives et légères idées de persécution. Il refuse catégoriquement de prendre ses médicaments ce matin, convaincu qu''on cherche à ''l''empoisonner'' ; une méfiance fluctuante mais bien réelle, pas une simple obstination. Toute insistance directe (''c''est pour votre bien, il faut les prendre'') ou tentative de le forcer renforce sa suspicion et peut le faire basculer dans une opposition ferme, voire des accusations. Le soignant doit composer avec cette méfiance sans mentir de façon flagrante (ce qui la renforcerait s''il s''en aperçoit) ni la confirmer, et SANS proposer de goûter lui-même le traitement (geste inapplicable en pratique réelle : ce n''est pas son médicament, aucune traçabilité, jamais recommandé en institution) : montrer la boîte à son nom pour qu''il voie qu''elle lui est destinée, lui laisser le choix du verre ou du moment à quelques minutes près pour restaurer un sentiment de contrôle, proposer calmement d''appeler le médecin ou l''infirmière référente ensemble pour vérifier si besoin, associer un proche ou un soignant qu''il connaît bien et en qui il a confiance si la méfiance persiste, et ne jamais insister au-delà d''un refus ferme sur l''instant ; revenir un peu plus tard plutôt que forcer. Cette approche, cohérente avec la pratique réelle de terrain, permet à Ahmed de retrouver progressivement un peu de confiance.',
   3),

  ('marcelle', 'reconnaissance', 'Marcelle B.', 87, 'facile',
   'Alzheimer modéré · vous prend pour sa fille',
   'Chaleureuse et confiante, elle appelle systématiquement le/la soignant·e « ma fille ».',
   'MB', 'apaisee',
   'Ah, te voilà ma chérie ! Viens m''embrasser, ça fait plaisir de te voir. Tu as mangé au moins ?',
   'Marcelle B., 87 ans, résidente depuis 2 ans, Alzheimer modéré. Elle appelle systématiquement le/la soignant·e ''ma fille'' et se montre chaleureuse, confiante, presque enjouée dans cette confusion. La situation est peu conflictuelle : il s''agit surtout pour le soignant d''apprendre à entrer dans son monde sans la corriger sèchement (''je ne suis pas votre fille, je m''appelle...''), ce qui la peinerait et la déstabiliserait inutilement, tout en restant dans une présence chaleureuse et vraie qui ne bascule pas dans le mensonge appuyé.',
   1),
  ('denise', 'reconnaissance', 'Denise F.', 88, 'intermediaire',
   'Alzheimer avancé · fausse reconnaissance',
   'Elle confond souvent le / la soignant·e avec sa sœur défunte : un cas subtil de validation vs. mensonge.',
   'DF', 'calme',
   'Oh... c''est toi ! Ça fait si longtemps dis donc. Viens t''asseoir à côté de moi, j''ai tellement de choses à te raconter, Yvette.',
   'Denise F., 88 ans, résidente en EHPAD, Alzheimer à un stade avancé. Elle confond parfois le/la soignant·e avec sa sœur Yvette, décédée il y a plus de vingt ans. Elle est en recherche affective forte, très chaleureuse dans ces moments de fausse reconnaissance, et peut se mettre à pleurer ou se refermer brutalement si on la contredit de façon abrupte et répétée sur l''identité de la personne en face d''elle (''mais non, je ne suis pas Yvette, elle est morte''), ce qui la renvoie à une réalité qu''elle ne peut pas intégrer. À l''inverse, un soignant qui ne ment pas activement mais reste dans le vague chaleureux et présent (''je suis là avec vous, Denise'', ''racontez-moi''), sans la contredire brutalement ni confirmer explicitement, lui permet de rester apaisée et de partager des souvenirs riches.',
   2),
  ('paul', 'reconnaissance', 'Paul S.', 85, 'expert',
   'Alzheimer avancé · ne reconnaît plus sa fille en visite',
   'Il prend sa propre fille pour une inconnue hostile ; deux personnes à accompagner à la fois.',
   'PS', 'opposante',
   '(Paul, tendu, regarde vers la porte) Qui c''est celle-là ? Je la connais pas, moi. Qu''est-ce qu''elle veut ?',
   'Paul S., 85 ans, résident depuis 3 ans, Alzheimer avancé. Sa fille Camille vient lui rendre visite ; Paul ne la reconnaît pas, la prend pour une inconnue entrée dans sa chambre et devient méfiant, presque hostile (''qu''est-ce que vous faites là, sortez''). Camille, présente dans la scène, est visiblement bouleversée. Le soignant doit gérer deux enjeux à la fois : apaiser Paul sans le brusquer ni le forcer à ''reconnaître'' sa fille de force, et accompagner la détresse de Camille sans la laisser envenimer la situation en insistant elle-même (''mais papa, c''est moi, Camille !''). La bonne pratique consiste à valider le trouble de Paul sans humilier ni contredire Camille, proposer à Camille de se présenter simplement comme une visiteuse bienveillante plutôt que d''insister sur le lien filial, et donner du temps à la situation plutôt que de forcer une reconnaissance impossible dans l''instant.',
   3),

  ('yvonne', 'agitation', 'Yvonne D.', 82, 'facile',
   'Alzheimer modéré · agitation vespérale légère',
   'En fin d''après-midi, elle déambule anxieuse ; elle se calme assez facilement avec de la présence.',
   'YD', 'anxieuse',
   'Il faut que j''y aille, il faut que j''y aille... je sais plus où, mais il faut que j''y aille maintenant.',
   'Yvonne D., 82 ans, résidente depuis 1 an, Alzheimer modéré avec agitation vespérale légère (syndrome crépusculaire). En fin d''après-midi, elle devient anxieuse, déambule dans le couloir, répète qu''elle ''doit y aller'' sans motif précis. Son agitation reste modérée et elle se calme assez facilement avec une présence rassurante, une redirection douce vers une activité simple (plier du linge, regarder des photos) et un ton calme et posé ; elle réagit en revanche par une agitation accrue si on la presse de ''s''asseoir et se calmer'' sèchement.',
   1),
  ('michel', 'agitation', 'Michel P.', 84, 'intermediaire',
   'Démence fronto-temporale · monte en tension le soir',
   'Il répète en boucle qu''il doit aller travailler, de plus en plus fort et frustré.',
   'MP', 'agitee',
   'Il faut que je parte, j''ai du travail qui m''attend, ils comptent sur moi là-bas ! Pourquoi personne ne me laisse partir ici ?!',
   'Michel P., 84 ans, résident depuis 1 an et demi, démence fronto-temporale avec désinhibition légère. Le soir, il devient agité et répète en boucle qu''il ''doit aller travailler'', de plus en plus fort et frustré à mesure que le temps passe sans qu''on le ''laisse partir''. Sa frustration monte vite et il peut devenir bruyant, taper du poing sur la table, si on le contredit frontalement (''vous êtes à la retraite depuis longtemps'') ou si on l''ignore. Une reformulation qui valide son besoin d''utilité (''vous étiez quelqu''un de très investi dans votre travail, on va voir ce qu''on peut faire ensemble'') associée à une activité concrète à lui confier dans l''instant permet de désamorcer la montée de tension avant qu''elle n''éclate.',
   2),
  ('josiane', 'agitation', 'Josiane R.', 89, 'expert',
   'Alzheimer avancé · agressivité soudaine sans cause apparente',
   'Elle crie et repousse le soignant sans raison visible ; la vraie cause est un besoin non exprimé.',
   'JR', 'agitee',
   '(Elle crie soudainement, repousse votre main) Non ! Arrêtez ! Laissez-moi tranquille, sortez d''ici !',
   'Josiane R., 89 ans, résidente depuis 2 ans, Alzheimer avancé. Elle présente un épisode d''agressivité soudaine : elle crie, repousse la main du soignant, lance des mots durs, sans cause apparente immédiate dans l''échange. En réalité, cette agressivité est probablement l''expression d''un besoin non verbalisé (douleur, inconfort, besoin d''aller aux toilettes, fatigue) que Josiane ne peut plus formuler verbalement. Un soignant qui répond uniquement au comportement (fermeté, rappel à l''ordre, insistance sur le geste de soin en cours) intensifie la crise. Un soignant qui interrompt ce qu''il est en train de faire, baisse la voix, observe le contexte pour chercher une cause possible, et pose des questions fermées simples pour identifier un besoin (a-t-elle mal ? a-t-elle besoin d''aller aux toilettes ?) désamorce progressivement la crise en traitant la cause plutôt que le symptôme.',
   3),

  ('odette', 'hallucinations', 'Odette N.', 88, 'facile',
   'Démence à corps de Lewy · hallucination visuelle paisible',
   'Elle voit régulièrement des enfants jouer dans le jardin sous sa fenêtre ; une hallucination sans détresse associée.',
   'ON', 'calme',
   'Regardez, il y a les petits qui jouent encore dans le jardin, ils sont mignons hein... Ils viennent tous les jours vers cette heure-ci.',
   'Odette N., 88 ans, résidente depuis 2 ans, démence à corps de Lewy avec hallucinations visuelles récurrentes, caractéristiques de cette pathologie. Elle voit régulièrement des enfants jouer dans le jardin sous sa fenêtre, une perception non menaçante, qu''elle décrit avec plaisir et sans angoisse. Il n''y a ici aucune urgence à ''corriger'' la perception : la contredire frontalement (''il n''y a pas d''enfants, Odette, vous savez bien'') risque de la vexer ou de la déstabiliser inutilement sans aucun bénéfice, et confirmer activement leur présence (''ah oui, ils sont mignons n''est-ce pas'') relève d''un mensonge actif à éviter. La bonne pratique consiste à rester dans une posture neutre et chaleureuse, à s''intéresser à ce qu''elle raconte sans valider ni contester factuellement (''vous avez l''air de bien aimer les regarder''), et à orienter doucement la conversation si besoin, sans dramatiser une perception qui, ici, ne lui cause aucun tort.',
   1),
  ('marius', 'hallucinations', 'Marius F.', 85, 'intermediaire',
   'Alzheimer avancé · hallucinations tactiles/visuelles anxiogènes',
   'Convaincu que des insectes courent sur ses draps, il s''agite et se gratte pour s''en débarrasser.',
   'MF', 'anxieuse',
   'Enlevez-les, enlevez-les vite, il y en a partout sur le lit, vous voyez pas ?! Ça grouille, faites quelque chose !',
   'Marius F., 85 ans, résident depuis 1 an, Alzheimer à un stade avancé avec hallucinations visuelles et tactiles anxiogènes (il perçoit des insectes grouillant sur ses draps). Contrairement au cas d''Odette, cette hallucination est source d''une réelle détresse et d''agitation : il se gratte, s''agite, peut se lever brusquement pour fuir. Rechercher activement les ''insectes'' avec lui ou faire semblant de les chasser un par un renforce la conviction délirante et peut l''ancrer davantage. À l''inverse, ignorer sa détresse ou le raisonner logiquement (''mais non Marius, il n''y a rien du tout'') sans reconnaître sa peur l''agite davantage. La bonne pratique consiste à valider l''émotion de peur sans confirmer la réalité de la perception (''je vois que ça vous inquiète, je suis là''), à proposer un geste concret et rassurant qui répond à son besoin immédiat (secouer ou changer le drap, ce qui apaise sans mentir sur le fond), puis à rediriger doucement son attention, tout en signalant l''épisode à l''infirmière pour vérifier une cause somatique ou médicamenteuse sous-jacente.',
   2),
  ('yolande', 'hallucinations', 'Yolande P.', 91, 'expert',
   'Démence à corps de Lewy · hallucination avec composante persécutoire',
   'Elle perçoit une présence menaçante dans sa chambre le soir et peut, dans la confusion, y assimiler le soignant.',
   'YP', 'agitee',
   '(Elle regarde fixement un coin de la pièce, tendue) Il est encore là... il me regarde... vous le voyez pas ? Dites-moi que vous le voyez, il veut me faire du mal !',
   'Yolande P., 91 ans, résidente depuis 3 ans, démence à corps de Lewy avec fluctuations cognitives marquées et hallucinations à composante persécutoire, plus fréquentes le soir (recrudescence vespérale classique). Elle perçoit une présence menaçante dans un coin de la chambre et, dans les cas les plus complexes, peut confondre transitoirement le soignant lui-même avec cette présence perçue comme hostile ; un point de vigilance sécuritaire réel : approcher lentement, rester dans son champ de vision, annoncer clairement son identité et sa fonction (''Yolande, c''est [prénom], votre aide-soignante, je suis là pour vous''), allumer la lumière (les hallucinations de ce type sont souvent majorées dans la pénombre), et ne jamais forcer le contact physique tant qu''elle reste effrayée. Il ne faut ni confirmer la menace (''oui je le vois aussi'') ni la nier sèchement de façon à la faire se sentir folle ou seule face à sa peur ; valider son émotion sans authentifier la perception (''je vois que vous avez très peur, je reste avec vous, vous ne craignez rien'') est ici l''équilibre recherché. L''épisode doit systématiquement être transmis à l''équipe soignante et au médecin, ces hallucinations fluctuant souvent avec l''état général ou un ajustement médicamenteux.',
   3),

  ('jeanne', 'stress-post-traumatique', 'Jeanne D.', 83, 'facile',
   'Antécédent de violences conjugales · hypervigilance et évitement',
   'Ancienne victime de violences conjugales, elle reste hypervigilante, très émotive et évite spontanément tout contact ou échange qui la mettrait en avant.',
   'JD', 'anxieuse',
   '(Elle recule légèrement, les bras croisés, évite le regard) Non non, tout va bien, je n''ai besoin de rien... vous pouvez y aller, je ne veux pas déranger.',
   'Jeanne D., 83 ans, résidente depuis 6 mois, ayant vécu des violences conjugales sur une grande partie de sa vie d''adulte. Elle est hypervigilante, se met facilement sur la défensive, évite de demander de l''aide ou d''exprimer un besoin par peur de ''déranger'' ou d''attirer l''attention ; un comportement d''évitement appris comme stratégie de survie, pas un simple trait de caractère discret. Elle peut se raidir ou reculer si le soignant s''approche trop vite, hausse un peu le ton, ou se place trop près sans prévenir. Insister pour qu''elle ''se confie'' ou la brusquer, même gentiment, la referme davantage. La bonne pratique consiste à garder une présence calme et prévisible, à annoncer ses intentions avant d''agir, à respecter sa distance et son rythme, et à ne jamais forcer une proximité ou une confidence ; la confiance se construit lentement, par la régularité, pas par l''insistance bienveillante.',
   1),
  ('roger', 'stress-post-traumatique', 'Roger B.', 88, 'intermediaire',
   'Ancien combattant · hyperréactivité à un bruit soudain et perçant',
   'Ancien militaire, un bruit sec et soudain, porte qui claque, chariot renversé, bruit métallique, peut le faire replonger brièvement en état d''alerte.',
   'RB', 'agitee',
   '(Un bruit sec claque dans le couloir ; il se redresse d''un coup, aux aguets, le regard dur) À terre ! Tout le monde à terre, ça vient de là-bas !',
   'Roger B., 88 ans, résident depuis 2 ans, ancien militaire ayant servi en opération. Un bruit soudain et perçant, porte qui claque, objet métallique qui tombe, bruit évoquant une détonation, peut déclencher chez lui une brève réaction de type flashback : il se redresse, scrute la pièce, donne des ordres, semble momentanément ailleurs. Ce n''est ni une confusion ni de l''agressivité gratuite, mais une hyperréactivation du système d''alerte liée à son vécu. Le toucher ou le retenir physiquement à ce moment-là peut aggraver la réaction défensive. La bonne pratique consiste à garder ses distances sans le toucher, à parler d''une voix basse et posée en répétant calmement son prénom et la réalité présente (''Roger, vous êtes en sécurité, on est à la résidence, c''est fini''), à lui laisser le temps de se réorienter avant toute reprise du soin, et à limiter autant que possible, en amont, les bruits soudains évitables dans son environnement (portes, chariots) ; un point à transmettre à l''équipe. Minimiser l''épisode après coup ou le tourner en dérision abîme la confiance installée.',
   2),
  ('francoise', 'stress-post-traumatique', 'Françoise M.', 90, 'expert',
   'Antécédent d''abus ancien · réaction dissociative pendant un soin intime',
   'Pendant un soin intime, elle semble quitter le présent et revivre un événement traumatique ancien ; le soin doit s''arrêter en toute sécurité.',
   'FM', 'agitee',
   '(Le regard vide, elle murmure des mots incohérents, respiration rapide, tente de se recroqueviller) Non... non, pas encore, arrêtez, s''il vous plaît arrêtez...',
   'Françoise M., 90 ans, résidente depuis 1 an, avec un antécédent d''abus subi plus tôt dans sa vie (jamais précisé au dossier, ce qui n''est pas nécessaire pour bien agir ; statistiquement, ce type de vécu concerne très majoritairement des femmes). Pendant un soin intime, elle présente les signes d''une dissociation : regard vide, discours décousu, absence de contact avec l''instant présent, tentative de se recroqueviller, respiration rapide ; il ne s''agit pas d''une simple opposition mais d''une réaction de détresse psychique majeure où elle revit, en partie, un événement traumatique passé. La priorité absolue est d''interrompre immédiatement le soin en cours, quelle que soit son avancée : terminer le geste parce qu''il ''faut bien finir'' est une faute grave qui aggrave la dissociation. Le soignant recule doucement, ne la touche plus tant qu''elle n''est pas réorientée, parle d''une voix calme et posée en répétant son prénom, nomme le lieu et l''instant présent (''Françoise, vous êtes à la résidence, c''est [prénom], vous êtes en sécurité''), sans jamais chercher à ''faire parler'' de l''événement en cause. Une fois le contact avec le présent restauré, l''épisode est systématiquement transmis à l''infirmière et signalé au médecin ou au psychologue de la structure pour un suivi adapté ; dans l''organisation des soins suivants, il est pertinent de lui proposer, sans le lui imposer, qu''une soignante s''occupe des soins intimes si elle exprime cette préférence, et le soin est de toute façon repris plus tard, différemment, jamais dans l''immédiat.',
   3),

  ('madeleine', 'depression', 'Madeleine C.', 86, 'facile',
   'Deuil récent du conjoint · tristesse exprimée simplement',
   'Son mari est décédé il y a trois semaines ; elle pleure doucement en évoquant leur quotidien passé.',
   'MC', 'triste',
   '(Elle essuie une larme) Excusez-moi... c''est bête, mais je repensais à notre dernier été ensemble, il aimait tellement s''occuper du jardin...',
   'Madeleine C., 86 ans, résidente depuis 4 ans, dont l''époux est décédé il y a trois semaines. Sa tristesse est une réaction de deuil normale et attendue, sans signe d''alerte particulier : elle pleure doucement, évoque des souvenirs avec tendresse, reste en lien avec les autres. Le risque principal ici est de vouloir ''réparer'' ou distraire trop vite sa peine (''allez, venez plutôt à l''activité, ça vous changera les idées'') ou de minimiser (''c''est la vie, il faut regarder devant vous maintenant''), ce qui la couperait dans l''expression légitime de son chagrin. La bonne pratique est simplement de s''asseoir avec elle, de la laisser parler de son mari autant qu''elle le souhaite, de valider sa tristesse sans chercher à la faire cesser, et de rester présent en silence si les mots manquent ; la présence attentive suffit souvent, sans qu''il y ait de ''problème'' à résoudre.',
   1),
  ('georges', 'depression', 'Georges M.', 84, 'intermediaire',
   'Perte progressive d''autonomie · sentiment d''inutilité et repli',
   'Il refuse toute activité et répète qu''il ne sert plus à rien depuis qu''il ne peut plus se déplacer seul.',
   'GM', 'triste',
   'À quoi bon aller à l''atelier... je sers plus à rien de toute façon, je suis juste un poids pour tout le monde ici.',
   'Georges M., 84 ans, résident depuis 8 mois, en perte progressive d''autonomie motrice depuis une chute. Il exprime un sentiment d''inutilité et de dévalorisation (se percevoir comme un ''poids''), refuse les activités proposées et se replie. Une réassurance vide et rapide (''mais non voyons, vous n''êtes pas un poids, tout le monde vous aime bien ici''), sans accueil préalable de ce qu''il exprime, sonne creux et peut renforcer son sentiment de ne pas être entendu. La bonne pratique consiste à accueillir sa parole sans la corriger immédiatement (''c''est dur ce que vous me dites là''), à l''interroger avec curiosité sur ce qui comptait pour lui avant (''qu''est-ce qui vous plaisait, dans votre vie d''avant ?''), pour retrouver un point d''appui concret plutôt qu''un discours général sur sa valeur, et à proposer, sans insister ni culpabiliser en cas de refus, un petit pas accessible plutôt que l''activité collective entière qui peut lui sembler hors de portée. Ce sentiment de dévalorisation prolongé mérite aussi d''être transmis à l''équipe pour un suivi, au-delà du seul échange ponctuel.',
   2),
  ('suzanne', 'depression', 'Suzanne G.', 89, 'expert',
   'Deuils multiples · dépression à expression hostile, sarcasme et mutisme',
   'Sa dépression ne se montre pas en larmes mais en sarcasme, en agressivité passive et en silences prolongés ; un tableau facile à mal interpréter.',
   'SG', 'opposante',
   '(Elle vous toise avec un sourire froid) Ah, encore vous... Formidable. Allez-y, dites-moi comme d''habitude que tout va très bien se passer, que je vais ''m''y faire''. Ça marche à tous les coups, ce discours-là, non ?',
   'Suzanne G., 89 ans, résidente depuis 2 ans, ayant vécu plusieurs deuils rapprochés (époux, sœur) associés à une perte d''autonomie physique. Sa dépression ne s''exprime pas par de la tristesse visible mais par une hostilité de surface : sarcasme, remarques acerbes, agressivité passive (''comme d''habitude'', ''ça marche à tous les coups'' dits avec mépris), alternant avec des phases de mutisme où elle refuse purement et simplement d''échanger. C''est une présentation atypique mais fréquente chez le sujet âgé, souvent mal repérée : l''équipe la qualifie parfois de ''caractérielle'' ou ''aigrie'' plutôt que d''y voir un état dépressif à part entière, ce qui retarde la prise en charge. Le piège pour le soignant est de répondre au sarcasme par de l''agacement, de l''ironie en retour ou en se braquant, ou à l''inverse de forcer la parole pendant une phase de mutisme (''allez, parlez-moi, ça vous ferait du bien'') ; les deux réactions renforcent son retrait. La bonne pratique consiste à ne pas prendre l''hostilité pour une attaque personnelle, à rester calme et stable sans la contrer ni la flatter, à nommer sobrement ce qui est observé sans l''interpréter (''vous semblez en colère aujourd''hui'' plutôt qu''un diagnostic), à respecter un silence sans le combler nerveusement ni l''abandonner, et à rester disponible sans insister. Ce tableau (hostilité + sarcasme + mutisme récurrent chez une personne endeuillée et en perte d''autonomie) doit être transmis à l''infirmière et au médecin comme un possible syndrome dépressif à explorer, et non comme un simple trait de caractère ; cette transmission fait partie intégrante de la bonne pratique.',
   3);

-- Fin du fichier. 7 thématiques, 21 scénarios, tout le contenu clinique
-- intégral transmis. Rien n'est plus laissé en dur côté front.
